"""Add borrower_name to BorrowRecord

Revision ID: b5eda58e9023
Revises: cd02b3bf7a06
Create Date: 2024-06-20 17:03:10.122764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eda58e9023'
down_revision = 'cd02b3bf7a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_record', schema=None) as batch_op:
        batch_op.drop_column('borrower_name')

    # ### end Alembic commands ###
