"""Add cascade delete to BorrowRecord

Revision ID: f21884b17ea5
Revises: 
Create Date: 2024-06-20 16:13:38.351496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21884b17ea5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_record', schema=None) as batch_op:
        batch_op.drop_constraint('borrow_record_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('borrow_record_ibfk_2', 'book', ['book_id'], ['id'])

    # ### end Alembic commands ###
